#!/bin/bash

domain1=${PWD}/flange_domain1
domain2=${PWD}/flange_domain2

solver1="laplacianFoam"
solver2="laplacianFoam"

numProcs=2 #ranks set to 2 for each domain

if [ -d "Logs" ]; 
then
  rm -rf Logs
fi

# clean and create domain1
cd ${domain1}
./Allclean
./Allpreprocess
cd ..

# clean and create domain2
cd ${domain2}
./Allclean
./Allpreprocess
cd ..

# Console output to files (1 per rank, so files .1.0 and .1.1 output from flange_domain1, files .1.2 and .1.3 output from flange_domain2)
#mpirun -np ${numProcs} --output-filename Logs/coupledOutput ${solver1} -case ${domain1} -parallel -coupled : -np ${numProcs} ${solver2} -case ${domain2} -parallel -coupled
mpirun -np ${numProcs} ${solver1} -case ${domain1} -parallel -coupled : -np ${numProcs} ${solver2} -case ${domain2} -parallel -coupled

# postprocess domain1
cd ${domain1}
./Allpostprocess
cd ..

# postprocess domain2
cd ${domain2}
./Allpostprocess
cd ..

