#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runAnsysToFoam()
{
    if [ -f log.ansysToFoam ]
    then
        echo "ansysToFoam already run on $PWD: remove log file to re-run"
    else
        echo "Running ansysToFoam: converting mesh $1"
        ansysToFoam ${FOAM_TUTORIALS:?}/resources/geometry/flange.ans -scale 0.001 > log.ansysToFoam 2>&1
    fi
}

runAnsysToFoam flange.ans 0.001
runApplication decomposePar

#------------------------------------------------------------------------------
